# Generated by Django 2.2.6 on 2020-09-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200905_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('M', 'manual'), ('A', 'automatic'), ('R', 'robot')]),
        ),
    ]
