# Generated by Django 2.2.6 on 2020-09-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200905_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('M', 'manual'), ('A', 'automatic'), ('R', 'robot')], default='A'),
        ),
    ]
