# Generated by Django 2.2.6 on 2020-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200905_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[(0, 'manual'), (1, 'automatic'), (2, 'robot')], default=0),
        ),
    ]
