# Generated by Django 2.2.6 on 2020-09-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20200905_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='producer',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
